### ISSUE TITLE
Small error in tutorial chapter 3

### ISSUE THREAD

**Issue by kaikoveritch** [cui-unige/swift#2]
In the "Inout Parameters" section a comment says:

> Note that this example just serves to illustrate the definition of inout parameters. Swift already has a 
> built-in `swapPokemon(_:_:)` function which should always be preferred.

I have a strong intuition that Swift does not have a built-in "swapPokemon" function, though it would be fun.

**Comment by kyouko-taiga** [comment]
fixed in e4849b367cb2badbabf40b734eeeeab26fea65ce
